services:
  # 1. Боти Телеграм
  - type: web
    name: pobeda-kargo-bot
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss
    startCommand: npx tsx src/index.ts
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NODE_VERSION
        value: "20.14.0"

  # 2. Панели Маъмурият (Next.js)
  - type: web
    name: pobeda-admin-panel
    env: node
    plan: free
    rootDir: admin-panel
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: "https://pobeda-admin-panel.onrender.com"
      - key: BOT_TOKEN
        sync: false
      - key: NODE_VERSION
        value: "20.14.0"

  # 3. Барномаи Сканер (Vite)
  - type: web
    name: pobeda-scanner-app
    env: static
    plan: free
    rootDir: scanner-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: "20.14.0"
