databases:
  - name: pobeda-db
    databaseName: pobeda_db
    user: pobeda_user
    plan: free

services:
  # 1. Боти Телеграм
  - type: web
    name: pobeda-kargo-bot
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push && npx ts-node src/index.ts
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: pobeda-db
          property: connectionString

  # 2. Панели Маъмурият (Next.js)
  - type: web
    name: pobeda-admin-panel
    env: node
    plan: free
    rootDir: admin-panel
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pobeda-db
          property: connectionString
